### ISSUE TITLE
Key rings

### ISSUE THREAD

**Issue by cyr3ne** [rakaw/cc-jamming#3]
What is this keyrings? I haven't seen that in any projects before. Is it for developer/user management? 
Good addition.

**Comment by rakaw** [comment]
This is a file encryption tool called Blackbox made by stackoverflow implementing GPG keys that i use to encrypt my notes and API keys in a separate file and upload to github. This way i can share my NOTES.md file and my API keys with multiple computers (needs linux vm on windows though).
